### ISSUE TITLE
Include link to update page in main interface?

### ISSUE THREAD

**Issue by LukePrior** [dl9rdz/rdz_ttgo_sonde#122]
Hello,

What do you think about adding a link to the OTA update page /update.html from the About tab in the main interface?

I think this would make it easier for new people to find and what would be even better is if we check what the latest version assuming we have an internet connection and display some update available text next to the current version number?

We might want some logic if the user is running stable or devel only to show them relevant updates?

![image](https://user-images.githubusercontent.com/22492406/128594370-9b9b0804-5fd2-4b3d-8502-65bedf0c123b.png)

Cheers

**Comment by dl9rdz** [comment]
Ok, I did a first step in this direction.

Travis-CI creates a HTML file with version info of the update on rdzsonde.mooo.com (== gh-pages on github)

I currently just include this as iframe on update.html. So the TTGO has no idea what the update version is, just the user's browser fetches that info. And the about tab has a link to update.html.

I guess that's fine for now. More sophisticated UI could probably done on the client side (browser) with some JavaScript. There is space on the file system for putting some js (or just enhancing style.css to make the update.html nicer), so that would fine, and it would not occupy code space on the TTGO.

**Comment by LukePrior** [comment]
@dl9rdz I have updated but I don't see the update text on the about page.

![image](https://user-images.githubusercontent.com/22492406/128619034-e8ae2d46-e709-4241-9102-ebb7180cd376.png)

The /update.html page does now show the version numbers in iframes, it would be good to make that request on the TTGO device and show the number without needing the iframes.

![image](https://user-images.githubusercontent.com/22492406/128619076-a37e6359-4e55-4ce9-a99a-3c415eb513fc.png)

**Comment by dl9rdz** [comment]
> @dl9rdz I have updated but I don't see the update text on the about page.

Yes, that is what the comment regarding the letters and numbers is about. The update only updates the software, not the files in the file system. The about page is a html file on the file system. You see that change only after a full re-flash or manually updating the file  (Because of that, the previous version is -B12, and the new one is -B13.)

**Comment by LukePrior** [comment]
> Yes, that is what the comment regarding the letters and numbers is about. The update only updates the software, not the files in the file system. The about page is a html file on the file system. You see that change only after a full re-flash or manually updating the file (Because of that, the previous version is -B12, and the new one is -B13.)

Oh yes, sorry all good now.

**Comment by dl9rdz** [comment]
Looks nicer now (still client side, but I guess thats just fine)
