### ISSUE TITLE
Feature Request: Add signal level and timestamp of the latest received frame to the LiveMap

### ISSUE THREAD

**Issue by dm5tt** [dl9rdz/rdz_ttgo_sonde#155]
Hello!

It would be great to see following informations on the LiveMap:

- Timestamp of the latest received frame
- Signal level (dBm?) of the latest frame

Thank you!
Holger / DM5TT

**Comment by eben80** [comment]
Something like this?
![2021-09-14 22_50_53-rdzTTGOSonde Server LiveMap](https://user-images.githubusercontent.com/2545460/133341289-9f19e742-9eb4-4cb5-b8a7-f1cb0ced7de9.png)
The problem I have with it is that the rssi is not tied to the received frame, but a realtime value.  This means that  the livemap thinks new frames are received because the rssi value changes, even if that is not the case, so the status indicators keep green when they should be yellow.
Maybe the experts know how to fix it? :)

**Comment by dm5tt** [comment]
Yep! That looks great!

But I can't help regarding the web interface :-( My knowledge is limited to embedded stuff.

**Comment by eben80** [comment]
I think @cixio brought us the livemap functionality.

**Comment by dl9rdz** [comment]
I had a look at the livemap implementation (which is not from me). It shows green dot if something changed, otherwise a yellow dot. So this is of course not suitable if RSSI is included (which is updated even if no new frame was decoded).

Probably the best option would be to include the decoder status. This is used by the Android app, and has three states (timeout=>nothing received; crc error=>valid sonde header detected, but not successfully decoded do to bit errors; ok).

A simpler alternative is to just check if lat/lon has changed. Even if the sonde is laying on the ground this should have some noise and thus change between frames. Or even more easily include and check the virtual frame counter (sondeInfo->vframe. Even for sonde types that do not have a frame counter, this is a value that changes on every frame that is received.

**Comment by dl9rdz** [comment]
Latest version sends res and vframe in live.json.
Also modified livemap.js such that it checks if data.res==0 instead of JSON.stringify(data) !=  JSON.stringify(last_data).

**Comment by eben80** [comment]
The live map wasn't displaying a received sonde for me this morning. No green dots. Is it just me? 😬

**Comment by dl9rdz** [comment]
Did you update to the latest latest version? 
(As I did one modification without increasing the version number, this means devel20210919 from after 20:30Z yesterday, not the devel20210919 that was there for two hours before, which had the "res" field in the wrong place, and thus could have the effect you describe)

**Comment by eben80** [comment]
Yes I think I missed your last commit. So I'll check it out with the latest
changes thank you.

**Comment by eben80** [comment]
I've created this PR for this and tested the functionality.
https://github.com/dl9rdz/rdz_ttgo_sonde/pull/182
I needed to change the structure of live.json to be able to use the rssi value.
The sonde detail will remain even if the signal is lost and I also added last heading.
![2021-09-20 20_34_40-rdzTTGOSonde Server LiveMap](https://user-images.githubusercontent.com/2545460/134058765-70ba0676-ce8e-41a3-a4f4-91c6a83609aa.png)
.

**Comment by eben80** [comment]
There's just one thing missing for me. Previously, if I left the ttgo on overnight and opened the live map from fresh in the morning, it would show the last position. Now it won't, because its only using the res value and not checking if there's any existing data. It would be nice if it loaded any data that is there when you first open the browser. For that to happen now, it would need to be actively receiving.

**Comment by dl9rdz** [comment]
Ah thanks. II hope with the latest commit I have restored the previous behaviour in this regard.

**Comment by eben80** [comment]
> Ah thanks. II hope with the latest commit I have restored the previous behaviour in this regard.

I meant missing on my own PR as well of course 😁

**Comment by LukePrior** [comment]
The map doesn't seem to show the current launch site and frequency when no sonde is being decoded at the top as it was previously.

![image](https://user-images.githubusercontent.com/22492406/134128788-41bd470d-cfd9-4daa-8f62-e0797f84aa31.png)

**Comment by eben80** [comment]
> The map doesn't seem to show the current launch site and frequency when no sonde is being decoded at the top as it was previously.
> 
> ![image](https://user-images.githubusercontent.com/22492406/134128788-41bd470d-cfd9-4daa-8f62-e0797f84aa31.png)

It's this:
`if (data.lat == '0.000000') { return false; }`

I'm changing my PR to fix the display of historical data at first browser launch, if it exists.

**Comment by dl9rdz** [comment]
Yes. I just removed it. But now lets wait for the PR. :)

**Comment by eben80** [comment]
:D OK just going to get an old sonde from my car to test.

**Comment by eben80** [comment]
OK I hope that's sufficient.
I tried to test for all scenarios I can think of and the only time you might get an anomaly is with rssi value if you have a cold start of the browser and previous data exists from live.json. It will give you the current rssi.
I think that's not a big deal though.

**Comment by LukePrior** [comment]
Seems good to me now.

**Comment by eben80** [comment]
@dm5tt do you have a chance to check? Can this one be closed?

**Comment by dm5tt** [comment]
Will check in 1.5 weeks, as In travelling at the Moment. Thanks all for the work!

**Comment by dm5tt** [comment]
Back! Looks great! Thank you guys/girls!

The added informations are really useful to improve the setup.
