### ISSUE TITLE
OLED Display Error on SCAN-Display

### ISSUE THREAD

**Issue by smarti2019** [dl9rdz/rdz_ttgo_sonde#220]
Since the master version there has been a problem with the representation in the SCAN display on OLED displays.
In the 3rd line, where the start locations are, the last part always remains when the frequency is changed. So e.g. from Norderney the Y remains.

**Comment by dl9rdz** [comment]
Should be fixed in deve20211010.

The updated code is compatible with old screen1.txt, so a simple update should be fine in almost all cases.

Previous versions have an issue if there is a name with non-ascii characters following a 16-character name (such as München after Hohenpeissenberg). This is fixed in the new version as well, but only if you update screens1.txt as well (which is not done by an OTA update)
