### ISSUE TITLE
T-Beam 1.1 - No GPS Data Displayed and Unresponsive Buttons

### ISSUE THREAD

**Issue by obi7zik** [dl9rdz/rdz_ttgo_sonde#454]
Buttons 1 and 2 do not change the display screen, and there is no GPS output. Although the red light blinks, no GPS data is displayed on the T-Beam 1.1. dev2: dev20240824-C3

**Comment by dl9rdz** [comment]
This is unusual and should work.  My test board is a T-Beam 1.2 with an AXP2101, and on this board the buttons work as usual (just checked). 

GPS *should* work as well but I rarely test it because indoor I have no GPS reception here.  What I remember is that the red GPS led starts blinking even if there is no GPS position yet. (I checked here, it was blinking with a sync to just 2 GPS satellites, which is good enough to get GPS time but not for getting the position). So the blinking does not necessarily mean you have a GPS position.  Maybe you just need to wait longer? (and the GPS antenna included in the T-Beam is not great either. Replacing it with a better GPS antenna makes quite a difference (in particular in locations with poor GPS reception).

Let me know more details of your setup. You are using the default auto configuration, or did you change anything? Is it the T-Beam with a small LCD display, or a larger TFT display?

**Comment by obi7zik** [comment]
The only change the display is a 1.3" OLED and configured as type 2 = OLED/SH1106 in the hardware settings to fix the slight alignment. 

I switching back to the previous firmware version, dev20240822-C3-full.bin, and everything worked, including the GPS and buttons. Although I noticed the buttons didn't respond once, they functioned properly after a reset.

I then switched back to the latest version again, and now everything is working correctly, including buttons 1 and 2, as well as the GPS data. Additionally, the issue in dev1, where APRS would send GPS location reports even when option 0 was selected, has been fixed. Thank you!"
