### ISSUE TITLE
tracking of DFM17

### ISSUE THREAD

**Issue by 14ri004** [dl9rdz/rdz_ttgo_sonde#456]
Hello, no tracking of DFM17 on Sondehub, decoding works but is not visible on Sondehub.

State: Connected: Waiting for ACK from server. Last upload start: -1 s ago Last reply: {"message": "some or all payloads could not be processed", "errors": [{"error_message": "rdzTTGOsonde branch and version was unable to be determined. We are unsure if this version handles DFM probes correctly. Please update to master 0.9.3, devel20230427 or later", "payload": {"software_name": "rdzTTGOsonde", "software_version": "dev20240901gps"

![dfm17](https://github.com/user-attachments/assets/0cc4e4e7-eb3b-4b25-a51a-ed1bb45867fc)

**Comment by dl9rdz** [comment]
I am aware of this issue. sondehub checks the version number, and fails to do so with the "new" (dev instead of devel) version numbers. This should be fixed at the sondehub side but that will take some while (I am in contact with them already), so next version will temporarily send "fake" version numbers as a temporary workaround.

**Comment by 14ri004** [comment]
OK, that was to let you know about the problem, THANK YOU
