### ISSUE TITLE
Feature Request: LMS6 radiosonde decoding

### ISSUE THREAD

**Issue by Shogoc** [dl9rdz/rdz_ttgo_sonde#48]
I'd like to request the capability to decode LMS6 radiosondes. Most of the NOAA radiosondes launched in my area are LMS6's. This is a super exciting project because of the lower-cost hardware and I think that our radiosonde tracking footprint could be significantly increased if we could leverage the TTGO hardware.

**Comment by bazjo** [comment]
As LMS6 are going to be phased out in the next 2-3 years and are to be replaced by RS41 and DFM-17, this feature would have an best before date right from its start

**Comment by dl9rdz** [comment]
It is unlikely that I will implement such a decoder, but of course I will consider pull requests with working decoders for inclusion (if memory footprint is not too excessive, which I don't think).  Hardware-wise it should work (for the 400 MHz version), as modulation seems to be FSK.

**Comment by kc0bqb** [comment]
I am curious if you have any more documentation for the SX1278FSK library.  I have started working on decoding the LMS6 radiosondes.  I am having some time understanding how to get the sx1278fsk library to recognize an lms6 packet.  I have changed the packet length (300) and sync (\x00\x58\xf3\x3f\xb8).

**Comment by trickv** [comment]
I happen to be on a trip staying by Cape Canaveral which launches LMS6 sondes frequently - presumably old school because it's the Space Force launching them.  They launch tons when rocket launches are on the roster.

My auto_rx station picks them up nicely but when one landed nearby I had wished for my ttgo to be able to grab it - and thought, "hey why not ask Claude how hard a port would be from the RS decoder" - turns out not terribly hard.

My branch: https://github.com/trickv/rdz_ttgo_sonde/tree/feat/lms6-403

I've been testing it live for a few days; once I've had a bit more energy to review it I may open a PR.
